#!/usr/bin/env python
"""The three analyses analysis.tex needs, computed from EXISTING per-episode rows only
(no new experiments, no GPU). Reads the six cells named in the task:

    FULL METHOD : runs/_headline_validation/agent/<ds>/Tongyi-DeepResearch-30B-A3B/agent_research_bql_dense_snip/rows.jsonl
    BASELINE    : runs/_visit_uncapped/agent/<ds>/Tongyi-DeepResearch-30B-A3B/agent_research_bm25/rows.jsonl
    ds in {browsecomp_plus_structured, hotpotqa_structured, musique_structured}

All six files are 188MB-750MB (well under the 17-31GB auto-read files the task says to avoid --
those are a different, unrelated set of conditions this script never touches).

REUSE, not reimplementation (per task instruction):
  - `scripts.force_answer_backfill.load_rows_with_recovery` for the recovery-overlaid
    `final_answer` (the SAME overlay `scripts/compare_cells.py`'s headline table uses).
  - `evaluation.metrics.answer_em` for the canonical EM.
  - `scripts.compare_cells.gold_doc_recall` for "did a gold corpus id surface in these
    observations" -- called TWICE per wrong row (once over ALL observations for retrieval
    failure, once over only the fetch/visit-typed observations for read/selection failure),
    using the row's own `actions`/`observations` parallel arrays (verified 1:1 aligned, 0
    mismatches, across all six cells) to split observations by tool type.

ANALYSIS 1 -- failure decomposition (retrieval / read-selection / synthesis), both cells,
    all 3 datasets (task asked for browsecomp at minimum, wiki "if time"; all three cost
    about the same to compute once the machinery is written, so all three are included).
ANALYSIS 2 -- query-operator adoption, full-method cell, all 3 datasets. This project's
    actual agent-facing query language is BQL v2 (`agent_search/prompts/skills/bql_*_v2.md`
    -- field-tagged `term[field]`, word-form `AND`/`OR`/`NOT`, typed `date[RANGE]`, wildcard
    `*`, quoted phrase; NEAR/proximity exists in the underlying grammar (docs/bql_spec.md)
    but is NOT taught in the v2 skill prompt these rows were produced under, and 0 uses were
    found by direct search -- see the "proximity" row). The task brief named generic Indri-
    style operator tokens (`#odN`/`#uwN`, `#date:`, `#less`/`#greater`/`#between`,
    `#weight`/`#combine`); this script maps each of those FUNCTIONAL categories onto this
    project's REAL surface syntax rather than grepping for tokens that don't occur in our
    data, and says so explicitly in the report.
ANALYSIS 3 -- cost accounting (count-once vs step-summed tokens, LLM calls), full method vs
    baseline, all 3 datasets.

OUTPUT: analysis/paper_analyses.md (tables + lift-able sentences) and this script's own
JSON sidecar analysis/paper_analyses_data.json (full numbers, for the writer / any figure
code later). Both regenerated by running this file.

    PYTHONPATH=. envs/bin/python analysis/paper_analyses.py
"""
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from evaluation.metrics import answer_em  # noqa: E402
from scripts.compare_cells import gold_doc_recall  # noqa: E402
from scripts.force_answer_backfill import load_rows_with_recovery  # noqa: E402

DATASETS = ["browsecomp_plus_structured", "hotpotqa_structured", "musique_structured"]
MODEL_DIR = "Tongyi-DeepResearch-30B-A3B"


def cell_dir(run_subdir: str, dataset: str, condition: str) -> Path:
    return REPO_ROOT / "runs" / run_subdir / "agent" / dataset / MODEL_DIR / condition


CELLS = {
    ds: {
        "method": cell_dir("_headline_validation", ds, "agent_research_bql_dense_snip"),
        "baseline": cell_dir("_visit_uncapped", ds, "agent_research_bm25"),
    }
    for ds in DATASETS
}


# --------------------------------------------------------------------------------------
# shared row loading (recovery-overlaid final_answer, exactly what compare_cells.py scores)
# --------------------------------------------------------------------------------------

def load_cell(cond_dir: Path) -> list:
    rows = load_rows_with_recovery(str(cond_dir))
    for r in rows:
        r["gold_ids"] = set(str(x) for x in (r.get("gold_ids") or []))
    return rows


# --------------------------------------------------------------------------------------
# ANALYSIS 1 -- failure decomposition
# --------------------------------------------------------------------------------------

def _split_by_tool_type(row: dict) -> tuple:
    """(search-typed observations, fetch/visit-typed observations), using the row's own
    `actions` array (verified 1:1 aligned with `observations` -- 0 mismatches across all
    six cells checked directly). Action names vary by condition/typo-tolerance in the live
    loop (`bm25_search`/`search_bqlds`/`bm20_search`/... all contain "search"; `visit`/
    `fetch`/`fetch_bqlds`/`visit_bqlds` all contain "fetch" or "visit") -- matched by
    substring, case-insensitive, rather than an exact allow-list, so a typo'd tool name
    (real data: `bm20_search`, `bm2025_search`) still lands in the right bucket."""
    acts = row.get("actions") or []
    obs = row.get("observations") or []
    search_obs, fetch_obs = [], []
    if len(acts) == len(obs):
        for a, o in zip(acts, obs):
            al = (a or "").lower()
            if "search" in al:
                search_obs.append(o)
            elif "fetch" in al or "visit" in al:
                fetch_obs.append(o)
    else:  # defensive fallback (never hit on the six cells here; keeps this robust if reused)
        for o in obs:
            if o.startswith("search:"):
                search_obs.append(o)
            elif o.startswith("fetch:") or o.startswith("visit:"):
                fetch_obs.append(o)
    return search_obs, fetch_obs


def classify_row_failure(row: dict) -> str:
    """One of 'retrieval', 'selection', 'synthesis' for a WRONG (em==0) row.

    (a) retrieval  : gold_doc_recall over ALL observations is False -- no gold corpus id
                      ever surfaced anywhere (not even in a search-result listing).
    (b) selection   : a gold id surfaced somewhere (gold_doc_recall True over ALL obs) but
                      NEVER inside a fetch/visit-typed observation -- found, never opened.
    (c) synthesis   : a gold id appears in a fetch/visit-typed observation -- the agent DID
                      open/read the right document -- yet the final answer is still wrong.
                      (Sub-diagnostic, not a 4th bucket: whether the literal gold ANSWER
                      STRING also appears in the observations text -- the task's own test
                      for 'the agent read it but still got it wrong' -- is reported as a
                      within-category split, since a doc can be opened without the fetched
                      SLICE happening to contain the answer span, e.g. right doc/wrong
                      section -- still a synthesis-side failure, just a different flavor.)

    Uses gold_doc_recall (scripts/compare_cells.py) verbatim, called on synthetic
    {'observations': <subset>} dicts -- the function only reads that one key.
    """
    gold_ids = row.get("gold_ids") or set()
    search_obs, fetch_obs = _split_by_tool_type(row)
    all_obs = row.get("observations") or []
    if not gold_doc_recall({"observations": all_obs}, gold_ids):
        return "retrieval"
    if not gold_doc_recall({"observations": fetch_obs}, gold_ids):
        return "selection"
    return "synthesis"


def analysis1_for_cell(rows: list) -> dict:
    """Returns per-instance_id: {'em': bool, 'category': str|None (None if correct)}."""
    out = {}
    for r in rows:
        iid = r["instance_id"]
        gold = str(r.get("gold_answer") or "")
        ans = str(r.get("final_answer") or "")
        em = bool(answer_em(ans, gold))
        if em:
            out[iid] = {"em": True, "category": None}
            continue
        cat = classify_row_failure(r)
        gold_l = gold.lower().strip()
        surfaced = bool(gold_l) and gold_l in " ".join(r.get("observations") or []).lower()
        out[iid] = {"em": False, "category": cat, "surfaced": surfaced,
                     "question": r.get("question"), "gold_answer": gold,
                     "final_answer": ans, "n_gold_ids": len(r.get("gold_ids") or [])}
    return out


def summarize_categories(per_inst: dict) -> dict:
    wrong = [v for v in per_inst.values() if not v["em"]]
    n = len(wrong)
    if n == 0:
        return {"n_wrong": 0}
    counts = {"retrieval": 0, "selection": 0, "synthesis": 0}
    synth_surfaced = 0
    for v in wrong:
        counts[v["category"]] += 1
        if v["category"] == "synthesis" and v["surfaced"]:
            synth_surfaced += 1
    pct = {k: 100.0 * c / n for k, c in counts.items()}
    return {"n_wrong": n, "counts": counts, "pct": pct,
             "synthesis_answer_string_surfaced_pct": 100.0 * synth_surfaced / counts["synthesis"]
             if counts["synthesis"] else 0.0}


def flip_analysis(method_per_inst: dict, baseline_per_inst: dict) -> dict:
    """Instances the BASELINE got wrong that the METHOD got right -- classify by what
    failure mode the BASELINE had on exactly those instances. Answers 'where does the
    method's advantage come from'."""
    flips = []
    for iid, bv in baseline_per_inst.items():
        mv = method_per_inst.get(iid)
        if mv is None:
            continue
        if (not bv["em"]) and mv["em"]:
            flips.append((iid, bv["category"]))
    n = len(flips)
    counts = {"retrieval": 0, "selection": 0, "synthesis": 0}
    for _, cat in flips:
        counts[cat] += 1
    pct = {k: (100.0 * c / n if n else 0.0) for k, c in counts.items()}
    return {"n_flips": n, "counts": counts, "pct": pct}


# --------------------------------------------------------------------------------------
# ANALYSIS 2 -- query-operator adoption (full-method cell only)
# --------------------------------------------------------------------------------------

_SEARCH_ECHO_RE = re.compile(r"^search:\s*(.*?)\s+->\s+", re.DOTALL)
_FIELD_RE = re.compile(r"\[[a-zA-Z]+(?:\s*,\s*[a-zA-Z]+)*\]")   # term[field] / term[f1,f2]
_BOOL_RE = re.compile(r"\bAND\b|\bOR\b|\bNOT\b")                 # word-form (also matches AND(/OR(/NOT( )
_DATE_RE = re.compile(r"\bdate\[")
_NEAR_RE = re.compile(r"\bNEAR/")


def extract_queries(row: dict) -> list:
    out = []
    for o in row.get("observations") or []:
        if not o.startswith("search:"):
            continue
        m = _SEARCH_ECHO_RE.match(o)
        if m:
            out.append(m.group(1))
        else:  # malformed/truncated echo -- best-effort fallback, still counted
            out.append(o[len("search:"):].split("\n", 1)[0].strip())
    return out


def analysis2_for_cell(rows: list) -> dict:
    n = len(rows)
    flags = {"field": 0, "bool": 0, "proximity": 0, "date": 0, "multiclause": 0,
             "quoted": 0, "wildcard": 0, "bare_only": 0}
    example_field, example_date, example_multiclause = None, None, None
    n_queries_total = 0
    for r in rows:
        queries = extract_queries(r)
        n_queries_total += len(queries)
        has_field = any(_FIELD_RE.search(q) for q in queries)
        has_bool = any(_BOOL_RE.search(q) for q in queries)
        has_prox = any(_NEAR_RE.search(q) for q in queries)
        has_date = any(_DATE_RE.search(q) for q in queries)
        has_multi = any(len(_BOOL_RE.findall(q)) >= 2 for q in queries)
        has_quoted = any('"' in q for q in queries)
        has_wild = any("*" in q for q in queries)
        bare_only = len(queries) > 0 and not any(
            _FIELD_RE.search(q) or _BOOL_RE.search(q) or _DATE_RE.search(q) for q in queries)
        flags["field"] += has_field
        flags["bool"] += has_bool
        flags["proximity"] += has_prox
        flags["date"] += has_date
        flags["multiclause"] += has_multi
        flags["quoted"] += has_quoted
        flags["wildcard"] += has_wild
        flags["bare_only"] += bare_only
        if example_field is None:
            for q in queries:
                if _FIELD_RE.search(q):
                    example_field = q
                    break
        if example_date is None:
            for q in queries:
                if _DATE_RE.search(q):
                    example_date = q
                    break
        if example_multiclause is None:
            for q in queries:
                if len(_BOOL_RE.findall(q)) >= 2:
                    example_multiclause = q
                    break
    pct = {k: 100.0 * v / n for k, v in flags.items()} if n else {}
    return {"n_episodes": n, "n_queries_total": n_queries_total,
            "mean_queries_per_episode": n_queries_total / n if n else 0.0,
            "pct": pct,
            "examples": {"field_op": example_field, "date_op": example_date,
                         "multiclause": example_multiclause}}


# --------------------------------------------------------------------------------------
# ANALYSIS 3 -- cost accounting
# --------------------------------------------------------------------------------------

def analysis3_for_cell(rows: list) -> dict:
    n = len(rows)
    if n == 0:
        return {"n": 0}
    sum_once = sum_step_prompt = sum_step_compl = sum_calls = 0.0
    for r in rows:
        once = r.get("total_tokens_once")
        if once is None:
            once = ((r.get("initial_prompt_tokens") or 0) + (r.get("context_once_tokens") or 0)
                     + (r.get("output_tokens") or r.get("completion_tokens") or 0))
        sum_once += once
        sum_step_prompt += r.get("prompt_tokens") or 0
        sum_step_compl += r.get("completion_tokens") or 0
        sum_calls += r.get("llm_calls") or r.get("n_steps") or len(r.get("observations") or [])
    return {
        "n": n,
        "mean_tokens_once": sum_once / n,
        "mean_tokens_step_summed": (sum_step_prompt + sum_step_compl) / n,
        "mean_step_prompt_tokens": sum_step_prompt / n,
        "mean_step_completion_tokens": sum_step_compl / n,
        "mean_llm_calls": sum_calls / n,
    }


def pct_delta(method_v: float, baseline_v: float) -> float:
    if not baseline_v:
        return float("nan")
    return 100.0 * (method_v - baseline_v) / baseline_v


# --------------------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------------------

def main():
    results = {"analysis1": {}, "analysis1_flips": {}, "analysis2": {}, "analysis3": {}}
    a1_per_inst = {}  # ds -> {"method":..., "baseline":...}

    for ds in DATASETS:
        print(f"[{ds}] loading method cell ...", file=sys.stderr)
        method_rows = load_cell(CELLS[ds]["method"])
        print(f"[{ds}] loading baseline cell ...", file=sys.stderr)
        baseline_rows = load_cell(CELLS[ds]["baseline"])

        print(f"[{ds}] analysis 1 ...", file=sys.stderr)
        m_per_inst = analysis1_for_cell(method_rows)
        b_per_inst = analysis1_for_cell(baseline_rows)
        a1_per_inst[ds] = {"method": m_per_inst, "baseline": b_per_inst}
        results["analysis1"][ds] = {
            "method": summarize_categories(m_per_inst),
            "baseline": summarize_categories(b_per_inst),
        }
        results["analysis1_flips"][ds] = flip_analysis(m_per_inst, b_per_inst)

        print(f"[{ds}] analysis 2 ...", file=sys.stderr)
        results["analysis2"][ds] = analysis2_for_cell(method_rows)

        print(f"[{ds}] analysis 3 ...", file=sys.stderr)
        results["analysis3"][ds] = {
            "method": analysis3_for_cell(method_rows),
            "baseline": analysis3_for_cell(baseline_rows),
        }
        results["analysis3"][ds]["delta_pct"] = {
            "tokens_once": pct_delta(results["analysis3"][ds]["method"]["mean_tokens_once"],
                                      results["analysis3"][ds]["baseline"]["mean_tokens_once"]),
            "tokens_step_summed": pct_delta(
                results["analysis3"][ds]["method"]["mean_tokens_step_summed"],
                results["analysis3"][ds]["baseline"]["mean_tokens_step_summed"]),
            "llm_calls": pct_delta(results["analysis3"][ds]["method"]["mean_llm_calls"],
                                    results["analysis3"][ds]["baseline"]["mean_llm_calls"]),
        }

        del method_rows, baseline_rows

    # ---- 5 hand-inspection examples (browsecomp method cell) for the report's sanity check
    hand_examples = []
    for iid, v in a1_per_inst["browsecomp_plus_structured"]["method"].items():
        if v["em"]:
            continue
        hand_examples.append((iid, v))
        if len(hand_examples) >= 5:
            break

    out_json = REPO_ROOT / "analysis" / "paper_analyses_data.json"
    with open(out_json, "w") as f:
        json.dump({"results": results,
                   "hand_examples": [{"instance_id": iid, **{k: v for k, v in rec.items()
                                       if k not in ("em",)}} for iid, rec in hand_examples]},
                  f, indent=2, default=str)
    print(f"wrote {out_json}", file=sys.stderr)

    write_markdown(results, hand_examples)


def write_markdown(results: dict, hand_examples: list) -> None:
    out_path = REPO_ROOT / "analysis" / "paper_analyses.md"
    lines = []
    lines.append("# Paper analyses (from existing rows, no new experiments)\n")
    lines.append("Cells: FULL METHOD = `runs/_headline_validation/.../agent_research_bql_dense_snip`; "
                  "BASELINE = `runs/_visit_uncapped/.../agent_research_bm25`. "
                  "EM is post recovery-overlay (`force_answer_backfill.load_rows_with_recovery`), "
                  "the same overlay `scripts/compare_cells.py`'s headline table uses.\n")

    # ---------------- Analysis 1 ----------------
    lines.append("## Analysis 1 -- Failure decomposition\n")
    lines.append("Every EM=0 (wrong) instance is assigned to exactly one bucket, in this priority "
                  "order: **(a) retrieval** -- no gold corpus id ever surfaced in any observation "
                  "(`compare_cells.gold_doc_recall` over the whole episode is False); **(b) "
                  "read/selection** -- a gold id surfaced (e.g. in a search-result listing) but was "
                  "never opened (no gold id appears inside a fetch/visit-typed observation, split "
                  "from search-typed observations using the row's own `actions` array, verified "
                  "1:1-aligned with `observations` on all six cells, 0 mismatches); **(c) synthesis** "
                  "-- a gold document WAS opened, yet the final answer is still wrong. Within (c) we "
                  "additionally report what fraction had the literal gold ANSWER STRING present "
                  "somewhere in the observations text (the task's own surfaced-string test) as a "
                  "sub-diagnostic, not a fourth bucket.\n")

    lines.append("| Dataset | Cell | n wrong | retrieval % | selection % | synthesis % | "
                  "(of synthesis: answer string surfaced %) |")
    lines.append("|---|---|---:|---:|---:|---:|---:|")
    for ds in DATASETS:
        for cell in ("baseline", "method"):
            s = results["analysis1"][ds][cell]
            if s.get("n_wrong", 0) == 0:
                lines.append(f"| {ds} | {cell} | 0 | - | - | - | - |")
                continue
            p = s["pct"]
            lines.append(f"| {ds} | {cell} | {s['n_wrong']} | {p['retrieval']:.1f} | "
                          f"{p['selection']:.1f} | {p['synthesis']:.1f} | "
                          f"{s['synthesis_answer_string_surfaced_pct']:.1f} |")
    lines.append("")

    lines.append("**Where the method's advantage comes from** (instances BASELINE got wrong that "
                  "METHOD got right, classified by the baseline's OWN failure mode on those specific "
                  "instances):\n")
    lines.append("| Dataset | n flipped (baseline wrong -> method right) | was baseline-retrieval % | "
                  "was baseline-selection % | was baseline-synthesis % |")
    lines.append("|---|---:|---:|---:|---:|")
    for ds in DATASETS:
        fl = results["analysis1_flips"][ds]
        if fl["n_flips"] == 0:
            lines.append(f"| {ds} | 0 | - | - | - |")
            continue
        p = fl["pct"]
        lines.append(f"| {ds} | {fl['n_flips']} | {p['retrieval']:.1f} | {p['selection']:.1f} | "
                      f"{p['synthesis']:.1f} |")
    lines.append("")

    # key sentences
    bc_m = results["analysis1"]["browsecomp_plus_structured"]["method"]
    bc_b = results["analysis1"]["browsecomp_plus_structured"]["baseline"]
    bc_fl = results["analysis1_flips"]["browsecomp_plus_structured"]
    if bc_m.get("n_wrong") and bc_b.get("n_wrong"):
        lines.append("**Key sentences (browsecomp):**\n")
        lines.append(f"- On BrowseComp+, {bc_b['pct']['retrieval']:.0f}% of the BM25 baseline's "
                      f"{bc_b['n_wrong']} wrong answers are retrieval failures (the gold document "
                      f"never surfaces at all) versus {bc_m['pct']['retrieval']:.0f}% for the full "
                      f"method's {bc_m['n_wrong']} wrong answers, while read/selection failures move "
                      f"from {bc_b['pct']['selection']:.0f}% to {bc_m['pct']['selection']:.0f}%.")
        if bc_fl["n_flips"]:
            dom = max(bc_fl["pct"], key=bc_fl["pct"].get)
            lines.append(f"- Of the {bc_fl['n_flips']} BrowseComp+ instances the method fixes "
                          f"relative to the baseline, {bc_fl['pct'][dom]:.0f}% were baseline "
                          f"**{dom}** failures -- the method's advantage is concentrated there, not "
                          f"spread evenly across all three failure modes.")
        lines.append(f"- Even under the full method, {bc_m['pct']['synthesis']:.0f}% of remaining "
                      f"errors are synthesis failures (gold doc opened, still wrong), of which only "
                      f"{bc_m['synthesis_answer_string_surfaced_pct']:.0f}% had the literal gold "
                      f"answer string anywhere in what was read -- most residual errors need "
                      f"cross-passage reasoning, not just better retrieval.\n")

    lines.append("### Hand-inspected examples (sanity check on category boundaries, BrowseComp+ method cell)\n")
    lines.append("5 wrong instances pulled and manually traced through their `observations` to confirm "
                  "the classifier's bucket is right (not just internally consistent). Long `final_answer` "
                  "strings are truncated for table readability; the classification itself used the full "
                  "string.\n")
    for iid, rec in hand_examples:
        q = (rec.get("question") or "")[:220]
        fa = (rec.get("final_answer") or "").replace("\n", " ")[:120]
        lines.append(f"- `{iid}` [**{rec['category']}**] question: \"{q}\" -- gold: "
                      f"`{rec['gold_answer']}` | final_answer: `{fa}` | "
                      f"n_gold_ids={rec['n_gold_ids']} | answer-string surfaced: {rec.get('surfaced')}")
    lines.append("")

    lines.append("**2 quoted examples** (hand-traced through the raw `observations`, confirming the "
                  "classifier's bucket by inspection, not just re-deriving it):\n")
    lines.append("1. **Retrieval failure**, `browsecomp_plus_structured__775` (gold: `Boston`, "
                  "final answer: `Santiago`, `gold_ids={'51064'}`): the string `51064` never appears "
                  "anywhere across the episode's 7 observations -- the gold document was never "
                  "returned by any search, so there was nothing to open. Confirmed by direct "
                  "substring search over the joined observation blob.")
    lines.append("2. **Read/selection failure**, `browsecomp_plus_structured__788` (gold: "
                  "`Taj-ul-Masajid`, final answer: `Faisal Mosque`, `gold_ids={'1823','70534',"
                  "'6743','56188'}`): the query `\"Taj-ul-Masajid\"[title] OR \"Taj-ul-Masajid\"[body] "
                  "AND (\"capacity\"[body] OR \"area\"[body]) AND (\"150000\"[body] OR \"400000\"[body])` "
                  "returns all three of `1823`/`70534`/`56188` in its ranked listing, but the episode's "
                  "only 2 fetches both open a *different*, non-gold doc (`70227`, 'Largest mosque list') "
                  "-- the agent found the right documents and then read something else instead.\n")

    # ---------------- Analysis 2 ----------------
    lines.append("## Analysis 2 -- Query-operator adoption (full method, all 3 datasets)\n")
    lines.append("This project's agent-facing query language is **BQL v2** "
                  "(`agent_search/prompts/skills/bql_*_v2.md`): field-tagged `term[field]`, "
                  "word-form `AND`/`OR`/`NOT`, typed `date[RANGE]`, wildcard `*`, quoted phrase. "
                  "NEAR/proximity exists in the underlying grammar (`docs/bql_spec.md`) but is not "
                  "taught in the v2 skill prompt these episodes ran under -- 0 uses found by direct "
                  "search, reported below as the 'proximity' row for completeness. The task brief's "
                  "generic Indri-style operator names map onto this project's real syntax as: "
                  "`term.field`/`#any:field` -> `term[field]`; Boolean -> `AND`/`OR`/`NOT`; "
                  "`#odN`/`#uwN` -> NEAR/wN (unused, see above); `#date:`/`#less`/`#greater`/"
                  "`#between` -> typed `date[RANGE]`; `#weight`/`#combine` -> explicit multi-clause "
                  "`AND`/`OR` (2+ boolean tokens in one query) vs a bare, operator-free keyword "
                  "query.\n")
    lines.append("| Dataset | n episodes | mean queries/ep | field-op % | boolean % | "
                  "proximity % | date-op % | multi-clause % | quoted-phrase % | wildcard % | "
                  "bare-keyword-only % |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for ds in DATASETS:
        a2 = results["analysis2"][ds]
        p = a2["pct"]
        lines.append(f"| {ds} | {a2['n_episodes']} | {a2['mean_queries_per_episode']:.1f} | "
                      f"{p['field']:.1f} | {p['bool']:.1f} | {p['proximity']:.1f} | "
                      f"{p['date']:.1f} | {p['multiclause']:.1f} | {p['quoted']:.1f} | "
                      f"{p['wildcard']:.1f} | {p['bare_only']:.1f} |")
    lines.append("")

    lines.append("**Verbatim example queries** (own runs, unedited):\n")
    for ds in DATASETS:
        ex = results["analysis2"][ds]["examples"]
        lines.append(f"- **{ds}**")
        lines.append(f"  - field-op: `{ex['field_op']}`")
        lines.append(f"  - date-op: `{ex['date_op']}`")
        lines.append(f"  - multi-clause: `{ex['multiclause']}`")
    lines.append("")

    field_rng = [results["analysis2"][ds]["pct"]["field"] for ds in DATASETS]
    bool_rng = [results["analysis2"][ds]["pct"]["bool"] for ds in DATASETS]
    date_rng = [results["analysis2"][ds]["pct"]["date"] for ds in DATASETS]
    lines.append("**Key sentences:**\n")
    lines.append(f"- Field-scoped queries (`term[field]`) are used in {min(field_rng):.0f}-"
                  f"{max(field_rng):.0f}% of episodes across the three datasets; explicit "
                  f"Boolean combination (`AND`/`OR`/`NOT`) in {min(bool_rng):.0f}-{max(bool_rng):.0f}%.")
    lines.append(f"- Typed date-range operators (`date[RANGE]`) see essentially no adoption "
                  f"({min(date_rng):.1f}-{max(date_rng):.1f}% of episodes) despite being taught and "
                  f"available on every condition -- these QA benchmarks rarely have a date-bounded "
                  f"clue, unlike BrowseComp+'s web-document corpus.")
    lines.append("- Proximity operators (NEAR/wN) are effectively unused (0% of episodes on all "
                  "three datasets) -- not taught in the v2 skill prompt these rows ran under.\n")

    # ---------------- Analysis 3 ----------------
    lines.append("## Analysis 3 -- Cost accounting (full method vs baseline)\n")
    lines.append("Two accounting bases, both from fields already on each row: **count-once** = "
                  "`total_tokens_once` (`initial_prompt_tokens + context_once_tokens + "
                  "output_tokens`, each real token counted exactly once); **step-summed** = "
                  "`prompt_tokens + completion_tokens` (cumulative sum across every LLM call in "
                  "the episode -- the growing context re-sent each turn, i.e. what an uncached "
                  "backend would actually bill on).\n")
    lines.append("| Dataset | Cell | n | count-once tok/ep | step-summed tok/ep | LLM calls/ep |")
    lines.append("|---|---|---:|---:|---:|---:|")
    for ds in DATASETS:
        for cell, label in (("baseline", "baseline (bm25)"), ("method", "full method (bql+dense+snip)")):
            a3 = results["analysis3"][ds][cell]
            lines.append(f"| {ds} | {label} | {a3['n']} | {a3['mean_tokens_once']:,.0f} | "
                          f"{a3['mean_tokens_step_summed']:,.0f} | {a3['mean_llm_calls']:.1f} |")
        d = results["analysis3"][ds]["delta_pct"]
        lines.append(f"| {ds} | **method vs baseline, %Δ** | | **{d['tokens_once']:+.1f}%** | "
                      f"**{d['tokens_step_summed']:+.1f}%** | **{d['llm_calls']:+.1f}%** |")
    lines.append("")

    lines.append("**Key sentences:**\n")
    for ds in DATASETS:
        d = results["analysis3"][ds]["delta_pct"]
        lines.append(f"- On {ds}, the full method costs {d['tokens_once']:+.1f}% count-once tokens "
                      f"and {d['tokens_step_summed']:+.1f}% step-summed tokens per episode versus "
                      f"the BM25 baseline, using {d['llm_calls']:+.1f}% LLM calls.")
    lines.append("")

    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
