#!/usr/bin/env python
"""Cross-backbone replication check: does the full-method-vs-baseline gap seen on the
primary backbone (Tongyi-DeepResearch-30B-A3B) replicate on the second backbone
(Qwen-AgentWorld-35B-A3B)?

Runs are STILL FILLING (browsecomp_plus_structured only, so far). This script is designed
to be re-run repeatedly against partial data and to REFUSE to over-claim while it is
partial:
  - every number is labelled "preliminary, n=X of <total>, not for publication" whenever
    either condition is <90% complete (a PROMINENT banner is also printed).
  - no significance test is computed on fewer than 200 shared (paired) instances — it
    prints "insufficient" instead of a p-value.
  - it always reports completion fraction per condition and n_shared, so a reader can see
    exactly how much data any number rests on.

Runs write to `runs/_xbackbone/agent/<ds>/<model>/<cond>/rows.jsonl` once merged, but land
in per-shard dirs under `runs/_xbackbone/__shards/<cond>/shard_*of10/agent/<ds>/<model>/<cond>/
rows.jsonl` until a merge step runs — this script reads BOTH and unions them, deduped by
instance_id (a canonical-dir row wins over a same-id shard row, on the assumption a row that
has been merged into the canonical file is the authoritative copy; among shard-only rows,
last-read-shard wins, which is a no-op in practice since a given instance_id should only ever
be assigned to one shard).

Usage (re-run any time; safe on 0 rows, partial rows, or a complete cell):
    PYTHONPATH=. envs/bin/python analysis/xbackbone_analysis.py
"""
from __future__ import annotations

import json
import sys
from hashlib import sha1
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from evaluation.metrics import answer_em  # noqa: E402
from scripts.compare_cells import load_judge_cache, mcnemar_p  # noqa: E402
from scripts.force_answer_backfill import load_rows_tolerant, needs_recovery  # noqa: E402

DATASET = "browsecomp_plus_structured"
MODEL_DIR = "Qwen-AgentWorld-35B-A3B"
XBB_ROOT = Path("runs/_xbackbone")
CONDITIONS = [  # (label, condition dir name)
    ("baseline (bm25)", "agent_research_bm25"),
    ("full method (bql_dense_snip)", "agent_research_bql_dense_snip"),
]
BASELINE_COND = "agent_research_bm25"
METHOD_COND = "agent_research_bql_dense_snip"

COMPLETE_THRESHOLD = 0.90          # below this fraction of TOTAL_N -> PARTIAL, preliminary labelling
MIN_N_FOR_SIGNIFICANCE = 200        # below this many SHARED (paired) instances -> "insufficient", no p-value

# The SAME comparison (full method minus SERP-bm25 baseline, paired EM, exact McNemar), already
# computed and reported on the PRIMARY backbone (Tongyi-DeepResearch-30B-A3B) via
# scripts/compare_cells.py over runs/_headline_validation (see comparison_result.md,
# browsecomp_plus_structured table: "bql+dense+snip fetch" row vs "SERP bm25 [BASELINE]" row).
# Hardcoded here (not recomputed) because it is a STABLE, already-published reference point this
# script's own partial numbers are compared AGAINST — recomputing it from the same partial-run
# machinery would be circular. If that primary-backbone number is ever revised, update this
# constant and its comment together.
PRIMARY_BACKBONE_REFERENCE = dict(
    backbone="Tongyi-DeepResearch-30B-A3B",
    em_method=38.9, em_baseline=36.4, delta_em=2.5, p_em=0.217, n=830,
    source="comparison_result.md (browsecomp_plus_structured: 'bql+dense+snip fetch' vs "
           "'SERP bm25 [BASELINE]'), generated by scripts/compare_cells.py from "
           "runs/_headline_validation",
)


def _dataset_total_n(dataset: str) -> int | None:
    """Total instance count for `dataset`, from data/<dataset>/queries.jsonl (one query per
    line) — the denominator for completion fraction. Returns None if the file can't be found/
    read, in which case callers fall back to the primary-backbone reference's n as a best-effort
    denominator and say so."""
    p = Path("data") / dataset / "queries.jsonl"
    if not p.exists():
        return None
    n = 0
    try:
        with p.open(encoding="utf-8") as fh:
            for line in fh:
                if line.strip():
                    n += 1
    except OSError:
        return None
    return n or None


def _cond_dirs(cond: str) -> tuple[Path, list[Path]]:
    """(canonical_dir, [shard_dirs...]) for `cond`, whether or not they currently contain data."""
    canonical = XBB_ROOT / "agent" / DATASET / MODEL_DIR / cond
    shard_glob = XBB_ROOT / "__shards" / cond
    shard_dirs = sorted(
        shard_glob.glob(f"shard_*of*/agent/{DATASET}/{MODEL_DIR}/{cond}")
    ) if shard_glob.exists() else []
    return canonical, shard_dirs


def _load_recovered_map(cond_dir: Path) -> dict:
    """instance_id -> recovered_answer for GENUINE recoveries in cond_dir's
    recovered_answers.jsonl sidecar, if present (same semantics as
    scripts/force_answer_backfill.load_rows_with_recovery's overlay filter)."""
    out: dict = {}
    p = cond_dir / "recovered_answers.jsonl"
    if not p.exists():
        return out
    for rec in load_rows_tolerant(str(p)):
        iid = rec.get("instance_id")
        if iid and not needs_recovery(rec.get("recovered_answer")):
            out[iid] = rec.get("recovered_answer") or ""
    return out


def load_condition(cond: str) -> dict:
    """instance_id -> row dict, unioning canonical + all shard rows.jsonl (dedup: canonical wins
    on a same-id collision), recovery-overlaid using EVERY recovered_answers.jsonl sidecar found
    across canonical + shard dirs (shards read first, canonical overlay wins on collision — same
    precedence as the row union itself, so overlay and row provenance never disagree about which
    copy is authoritative)."""
    canonical_dir, shard_dirs = _cond_dirs(cond)
    all_dirs = shard_dirs + [canonical_dir]  # canonical LAST -> wins on dict overwrite

    rows_by_id: dict = {}
    for d in all_dirs:
        rp = d / "rows.jsonl"
        if not rp.exists():
            continue
        for r in load_rows_tolerant(str(rp)):
            iid = r.get("instance_id")
            if iid:
                rows_by_id[iid] = r

    recovered_by_id: dict = {}
    for d in all_dirs:
        recovered_by_id.update(_load_recovered_map(d))

    judge_cache: dict = {}
    for d in all_dirs:
        judge_cache.update(load_judge_cache(d))

    out = {}
    for iid, r in rows_by_id.items():
        gold = str(r.get("gold_answer") or "")
        ans_raw = str(r.get("final_answer") or "")
        ans, recovered = ans_raw, False
        if needs_recovery(ans_raw):
            rec = recovered_by_id.get(iid)
            if rec is not None:
                ans, recovered = rec, True
        out[iid] = dict(
            em=bool(answer_em(ans, gold)),
            empty=needs_recovery(ans),
            recovered=recovered,
            judge=judge_cache.get((iid, sha1(ans.strip().encode()).hexdigest())),
        )
    return out


def pct(xs) -> float:
    return 100.0 * sum(xs) / len(xs) if xs else 0.0


def main() -> int:
    total_n = _dataset_total_n(DATASET)
    denom_note = ""
    if total_n is None:
        total_n = PRIMARY_BACKBONE_REFERENCE["n"]
        denom_note = (f" (data/{DATASET}/queries.jsonl not found — using the primary-backbone "
                       f"reference's n={total_n} as the denominator; verify this matches the "
                       f"dataset's true size)")

    metrics_by_cond = {cond: load_condition(cond) for _, cond in CONDITIONS}
    n_by_cond = {cond: len(m) for cond, m in metrics_by_cond.items()}
    frac_by_cond = {cond: (n_by_cond[cond] / total_n if total_n else 0.0) for cond, _ in metrics_by_cond.items()}

    is_partial = any(frac_by_cond[cond] < COMPLETE_THRESHOLD for _, cond in CONDITIONS)

    print("=" * 78)
    print(f"CROSS-BACKBONE ANALYSIS — {MODEL_DIR} / {DATASET}")
    print(f"total_n = {total_n}{denom_note}")
    print("=" * 78)

    if is_partial:
        print()
        print("#" * 78)
        print("#  PARTIAL RUN WARNING")
        print("#  One or both conditions are below the "
              f"{int(COMPLETE_THRESHOLD*100)}% completion threshold.")
        print("#  EVERY number below is preliminary and NOT FOR PUBLICATION.")
        print("#" * 78)

    print("\n--- per-condition completion ---")
    for label, cond in CONDITIONS:
        n = n_by_cond[cond]
        frac = frac_by_cond[cond]
        tag = "PARTIAL" if frac < COMPLETE_THRESHOLD else "complete"
        canonical_dir, shard_dirs = _cond_dirs(cond)
        n_canonical = len(load_rows_tolerant(str(canonical_dir / "rows.jsonl"))) \
            if (canonical_dir / "rows.jsonl").exists() else 0
        n_shards = n - n_canonical if n >= n_canonical else n  # approx (post-dedup n vs raw canonical count)
        print(f"  {label:32s} n={n:4d} of {total_n} ({100*frac:5.1f}%)  [{tag}]"
              f"   canonical_rows={n_canonical}  shard_dirs_found={len(shard_dirs)}")

    def _label(cond):
        return f"preliminary, n={n_by_cond[cond]} of {total_n}, not for publication" \
            if frac_by_cond[cond] < COMPLETE_THRESHOLD else f"n={n_by_cond[cond]} of {total_n}"

    print("\n--- per-condition EM (unpaired, all loaded rows) ---")
    em_by_cond = {}
    for label, cond in CONDITIONS:
        m = metrics_by_cond[cond]
        em = pct([v["em"] for v in m.values()]) if m else float("nan")
        em_by_cond[cond] = em
        print(f"  {label:32s} EM={em:5.1f}%   ({_label(cond)})")

    print("\n--- paired comparison: full method minus baseline, on SHARED instance_ids ---")
    base_m = metrics_by_cond[BASELINE_COND]
    meth_m = metrics_by_cond[METHOD_COND]
    shared = sorted(set(base_m) & set(meth_m))
    n_shared = len(shared)
    print(f"  n_shared = {n_shared}")

    result = dict(
        dataset=DATASET, model=MODEL_DIR, total_n=total_n,
        n_baseline=n_by_cond[BASELINE_COND], n_method=n_by_cond[METHOD_COND],
        frac_baseline=frac_by_cond[BASELINE_COND], frac_method=frac_by_cond[METHOD_COND],
        is_partial=is_partial, n_shared=n_shared,
        em_baseline=em_by_cond[BASELINE_COND], em_method=em_by_cond[METHOD_COND],
    )

    if n_shared < MIN_N_FOR_SIGNIFICANCE:
        print(f"  insufficient — fewer than {MIN_N_FOR_SIGNIFICANCE} shared instances "
              "(no significance test computed)")
        result.update(significance="insufficient")
    else:
        em_base_shared = pct([base_m[i]["em"] for i in shared])
        em_meth_shared = pct([meth_m[i]["em"] for i in shared])
        b = sum(1 for i in shared if meth_m[i]["em"] and not base_m[i]["em"])
        c = sum(1 for i in shared if base_m[i]["em"] and not meth_m[i]["em"])
        p = float(mcnemar_p(b, c))  # cast off scipy's numpy scalar type (not JSON-serializable as-is)
        delta = em_meth_shared - em_base_shared
        preliminary_tag = " [PRELIMINARY]" if is_partial else ""
        print(f"  EM (shared) baseline={em_base_shared:.1f}  method={em_meth_shared:.1f}  "
              f"delta={delta:+.1f}  discordant(method_only={b}, baseline_only={c})  "
              f"p={p:.3g}{preliminary_tag}")
        result.update(significance="computed", em_baseline_shared=em_base_shared,
                       em_method_shared=em_meth_shared, delta_em=delta,
                       b_method_only=b, c_baseline_only=c, p_em=p)

        print("\n--- replication check vs primary backbone ---")
        ref = PRIMARY_BACKBONE_REFERENCE
        print(f"  primary backbone ({ref['backbone']}): delta={ref['delta_em']:+.1f} "
              f"(method {ref['em_method']:.1f} vs baseline {ref['em_baseline']:.1f}), "
              f"p={ref['p_em']:.3g}, n={ref['n']}")
        print(f"  this backbone   ({MODEL_DIR}): delta={delta:+.1f} "
              f"(method {em_meth_shared:.1f} vs baseline {em_base_shared:.1f}), "
              f"p={p:.3g}, n={n_shared}{preliminary_tag}")
        same_direction = bool((delta > 0) == (ref["delta_em"] > 0))
        both_sig = bool(p < 0.05 and ref["p_em"] < 0.05)
        both_nonsig_same_dir = bool(p >= 0.05 and ref["p_em"] >= 0.05 and same_direction)
        if same_direction:
            direction_note = "SAME direction as the primary backbone (method beats baseline)" \
                if ref["delta_em"] > 0 else \
                "SAME direction as the primary backbone (baseline beats method)"
        else:
            direction_note = "OPPOSITE direction from the primary backbone"
        mag_ratio = (delta / ref["delta_em"]) if ref["delta_em"] else float("nan")
        print(f"  -> {direction_note}; magnitude {delta:+.1f} vs primary's {ref['delta_em']:+.1f} "
              f"pts (ratio {mag_ratio:.2f}x).")
        if is_partial:
            print("  -> NOTE: this backbone's numbers are PRELIMINARY (partial run) — treat this "
                  "replication read as directional only, not a confirmed result.")
        result.update(
            replication_same_direction=same_direction, replication_magnitude_ratio=mag_ratio,
            replication_both_significant=both_sig,
            replication_both_nonsig_same_direction=both_nonsig_same_dir,
            primary_backbone_reference=ref,
        )

    out_path = Path(__file__).resolve().parent / "xbackbone_analysis_data.json"
    out_path.write_text(json.dumps(result, indent=2))
    print(f"\nwrote {out_path}")
    if is_partial:
        print("\n" + "#" * 78)
        print("#  REMINDER: run was PARTIAL. Do not cite these numbers in the paper.")
        print("#  Re-run this script (PYTHONPATH=. envs/bin/python analysis/xbackbone_analysis.py)")
        print("#  once runs/_xbackbone fills further.")
        print("#" * 78)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
